src/components/home-banner/home-banner.js

smartcitiesdata/discovery_ui#250
co-authored-by: Cameron Marsh <cmarsh@pillartechnology.com>

Change redirect link to base url in header about icon

---

nginx-default.conf

smartcolumbusos/joomla-deploy#5

Headers for iframe and caching

---

nginx-default.conf

smartcolumbusos/joomla-deploy#5

Pragma Header

---

package-lock.json
package.json

smartcitiesdata/discovery_ui#193
co-authored-by: Sukaant Chaudhary <sukaant.chaudhary@gmail.com>

Version Bummp for bug fix

---

src/components/header/header.js
src/components/header/header.scss
src/components/nav-dropdown/nav-dropdown.scss

Also did a quick fix to min-width of dropdown css.
co-authored-by: Jake Clark <jake.clark@gmail.com>

Update nav items to match prod

---

package-lock.json
package.json

just a version bump
co-authored-by: Jake Prem <jakeprem@gmail.com>

Upgrade react-discovery-ui to 0.2.4 - Tabs Update

---

package-lock.json
package.json

0.2.5 includes bugfixes for tabs
co-authored-by: Jake Prem <jakeprem@gmail.com>

Upgrade react-discovery-ui version to the newest

---

.travis.yml
README.md
package-lock.json
package.json

smartcolumbusos/discovery_ui#13
co-authored-by: Richard Jones <rajones@hntb.com>

Updated files to rename "discovery" back to "discovery_ui" to be consistent with expected naming.

---

package-lock.json
package.json

smartcolumbusos/discovery_ui#8
co-authored-by: Cameron Marsh <cmarsh@pillartechnology.com>

updated to version 0.4.1

---

package-lock.json
package.json

smartcolumbusos/discovery_ui#8
co-authored-by: Kenny Drobnack <kdrobnack@pillartechnology.com>

Bump react-discovery-ui to 0.4.2

---

package-lock.json
package.json

smartcitiesdata/react_discovery_ui#43
co-authored-by: ManApart <akucera@pillartechnology.com>

Back button fixes from react_discovery_ui

---

package-lock.json
package.json

smartcitiesdata/react-discovery-ui#69
co-authored-by: Richard Jones <rajones@hntb.com>

Update version of react discovery ui

---

package-lock.json
package.json

smartcitiesdata/react-discovery-ui#27
co-authored-by: Richard Jones <rajones@hntb.com>

Update react discovery ui

---

package-lock.json
package.json

smartcitiesdata/react-discovery-ui#27
co-authored-by: Richard Jones <rajones@hntb.com>

Bump that version!

---

package-lock.json
package.json

smartcitiesdata/smartcitiesdata#220
co-authored-by: Kenny Drobnack <kdrobnack@pillartechnology.com>

Bump version of react-discovery-ui

---

package-lock.json
package.json

smartcitiesdata/react_discovery_ui#93

Bump version of react_discovery_ui

---

src/components/footer/footer.js
src/components/header/header.js
src/components/home-banner/home-banner.js

joomla requires the www and provides a redirect so this saves one hop for the user.

Add www. to links that redirect to joomla site

---

package-lock.json
package.json

smartcitiesdata/smartcitiesdata#289
co-authored-by: Benjamin Brewer <benjamin.brewer@accenture.com>

bumped to version 0.5.1 of react-discovery-ui

---

package-lock.json
package.json

smartcitiesdata/react_discovery_ui#94
co-authored-by: Benjamin <benjamin.brewer@accenture.com>

bump version to one that includes chart loading for visualizations

---

package-lock.json
package.json

smartcitiesdata/react_discovery_ui#73

Bump react-discovery-ui version

---

package-lock.json
package.json

smartcolumbusos/discovery_ui#26

Bump version of react discovery ui

---

package-lock.json
package.json

smartcolumbusos/discovery_ui#26

Bump version of react-disco

---

package-lock.json
package.json

smartcolumbusos/discovery_ui
co-authored-by: Scott Millard <smillard@hntb.com>

update react discovery ui version

---

package-lock.json
package.json

smartcitiesdata/react-discovery-ui#114
co-authored-by: Nathaniel Stevens <nstevens@pillartechnology.com>

Bumps react-discovery-ui version

---

package-lock.json
package.json

Updates the react component library to correctly display columns with names containing dot (.) characters (by passing an accessor to react-table.

Updating react component handling of column names with dots

---

nginx-default.conf

smartcolumbusos/scosopedia#140

add extra settings so auth0 works

---

nginx-default.conf

smartcolumbusos/scosopedia#140

update csp to allow mapbox to work for plotly

---

Dockerfile
nginx-default.conf
run.sh

smartcolumbusos/scosopedia#140

add configurable csp hosts variable

---

nginx-default.conf

smartcolumbusos/scosopedia#140

staging configuration includes a tracking pixel that dev doesn't have :|

---

package-lock.json
package.json

smartcolumbusos/discovery_ui#20
co-authored-by: Scott Millard <smillard@hntb.com>

version bump to 0.12.0

---

package-lock.json
package.json

co-authored-by: Cam Marsh <cmarsh@pillartechnology.com>

Update version to 0.12.1

---

src/components/footer/footer.js
src/components/footer/footer.scss

Added Tableau Web Connector Link to footer to match Joomla site.

Adding Tableau Web Connector Link to footer

---

package-lock.json
package.json

smartcitiesdata/smartcitiesdata#541

Bump react discovery ui to version 0.15.1

---

src/components/footer/footer.js
src/components/header/header.js

Removed Privacy Policy from header

Adding Terms of use and Privacy Policy to footer. 
